### ISSUE TITLE
/Users/felipehaller/Downloads/CryptoTrackMultiPlatformSwiftUI-main/CryptoTrackSwiftUIMultiPlatform/Shared/Services/ImageDownloadService.swift:58:31 Cannot find 'LocalFileManager' in scope

### ISSUE THREAD

**Issue by itsfelipeh** [barisozgenn/CryptoTrackMultiPlatformSwiftUI#1]
Build input file cannot be found: '/Downloads/CryptoTrackMacSwiftUI/CryptoTrackMacSwiftUI/CryptoTrackMacSwiftUI/Utils/LocalFileManager.swift'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

Hello, thank you very much for this project, just what I was looking for, but when running in xcode I get that error, I think the file is missing. could you help me. Thank you.
<img width="259" alt="Captura de pantalla 2022-12-02 a las 12 41 20" src="https://user-images.githubusercontent.com/11917772/205331099-9690bdba-70ae-4274-bc92-51df5baba3f0.png">
<img width="283" alt="Captura de pantalla 2022-12-02 a las 12 42 05" src="https://user-images.githubusercontent.com/11917772/205331118-1d48226c-44b4-4231-ac55-6cf9e998d234.png">

**Comment by barisozgenn** [comment]
Hi Felipe,
Oops, I was using both OS and Xcode beta, probably something went wrong. I will be sending the Local File Manager in the attachment. If you just re-import and click for all target memberships (**except widget**), it will be resolved. Many thanks for your feedback!

[LocalFileManager.swift](https://github.com/barisozgenn/CryptoTrackMultiPlatformSwiftUI/files/10143347/LocalFileManager.swift.zip)

**Comment by itsfelipeh** [comment]
Thank you! That's how it went.
